import React from "react";

const sizeClasses = {
  txtCaustenSemiBold22Gray80002: "font-causten font-semibold",
  txtCoreSansC65Bold19816: "font-coresansc font-semibold",
  txtCaustenSemiBold16Gray600: "font-causten font-semibold",
  txtCoreSansC65Bold24: "font-coresansc font-semibold",
  txtPoppinsMedium1341: "font-medium font-poppins",
  txtCoreSansC65Bold22: "font-coresansc font-semibold",
  txtCaustenSemiBold18Gray600: "font-causten font-semibold",
  txtCaustenSemiBold22DeeppurpleA200: "font-causten font-semibold",
  txtCoreSansC65Bold20: "font-coresansc font-semibold",
  txtCaustenSemiBold18Gray800: "font-causten font-semibold",
  txtCaustenMedium18WhiteA700: "font-causten font-medium",
  txtCaustenSemiBold14Gray800: "font-causten font-semibold",
  txtPoppinsMedium1788: "font-medium font-poppins",
  txtCaustenBold22Gray600: "font-bold font-causten",
  txtCaustenMedium22: "font-causten font-medium",
  txtCaustenSemiBold14Gray600: "font-causten font-semibold",
  txtCaustenRegular16RedA700: "font-causten font-normal",
  txtCaustenMedium22Gray60001: "font-causten font-medium",
  txtCoreSansC65Bold28: "font-coresansc font-semibold",
  txtUbuntuRegular22: "font-normal font-ubuntu",
  txtCaustenSemiBold14Gray400: "font-causten font-semibold",
  txtCoreSansC75ExtraBold34: "font-coresansc font-extrabold",
  txtCoreSansC65Bold28Gray800: "font-coresansc font-semibold",
  txtCoreSansC45Regular18: "font-coresansc font-normal",
  txtCaustenMedium22Gray800: "font-causten font-medium",
  txtCaustenBold18: "font-bold font-causten",
  txtCaustenSemiBold18WhiteA700: "font-causten font-semibold",
  txtCaustenMedium18Gray100: "font-causten font-medium",
  txtCaustenSemiBold16Bluegray400: "font-causten font-semibold",
  txtCaustenBold14: "font-bold font-causten",
  txtCaustenRegular18WhiteA700: "font-causten font-normal",
  txtCoreSansC65Bold34: "font-coresansc font-semibold",
  txtCaustenMedium18: "font-causten font-medium",
  txtCaustenRegular10: "font-causten font-normal",
  txtCoreSansC65Bold32: "font-coresansc font-semibold",
  txtCaustenMedium14WhiteA700: "font-causten font-medium",
  txtManropeRegular1546: "font-manrope font-normal",
  txtCoreSansC65Bold30: "font-coresansc font-semibold",
  txtCaustenMedium14: "font-causten font-medium",
  txtCoreSansC55Medium16: "font-coresansc font-medium",
  txtCaustenRegular14: "font-causten font-normal",
  txtCaustenMedium16: "font-causten font-medium",
  txtCaustenSemiBold14Black900: "font-causten font-semibold",
  txtCaustenMedium10: "font-causten font-medium",
  txtCaustenMedium12: "font-causten font-medium",
  txtCoreSansC65Bold34Bluegray900: "font-coresansc font-semibold",
  txtCaustenBold20: "font-bold font-causten",
  txtCaustenSemiBold24: "font-causten font-semibold",
  txtCaustenBold22: "font-bold font-causten",
  txtCaustenSemiBold22: "font-causten font-semibold",
  txtCaustenSemiBold20: "font-causten font-semibold",
  txtCoreSansC85Heavy50: "font-coresansc font-extrabold",
  txtCaustenRegular18Gray600: "font-causten font-normal",
  txtCaustenRegular16Gray600: "font-causten font-normal",
  txtCaustenRegular18: "font-causten font-normal",
  txtCaustenRegular16: "font-causten font-normal",
  txtCaustenMedium16Gray700cc: "font-causten font-medium",
  txtCaustenSemiBold14Bluegray400: "font-causten font-semibold",
  txtCaustenBold18Gray800: "font-bold font-causten",
  txtCaustenRegular20: "font-causten font-normal",
  txtCaustenRegular24: "font-causten font-normal",
  txtCoreSansC55Medium22: "font-coresansc font-medium",
  txtCoreSansC65Bold19816Bluegray90001: "font-coresansc font-semibold",
  txtCaustenRegular18Bluegray900: "font-causten font-normal",
  txtCaustenLight20: "font-causten font-light",
  txtCaustenBold18Gray400: "font-bold font-causten",
  txtCaustenBold14Gray600: "font-bold font-causten",
  txtCaustenSemiBold14: "font-causten font-semibold",
  txtCaustenMedium16Gray800: "font-causten font-medium",
  txtCaustenBold18Black900: "font-bold font-causten",
  txtManropeSemiBold2126: "font-manrope font-semibold",
  txtCaustenSemiBold22Gray800: "font-causten font-semibold",
  txtCaustenSemiBold18: "font-causten font-semibold",
  txtCaustenMedium18Gray600: "font-causten font-medium",
  txtCaustenMedium14Gray600: "font-causten font-medium",
  txtCaustenSemiBold16: "font-causten font-semibold",
  txtCaustenMedium22WhiteA700: "font-causten font-medium",
  txtCaustenBold2858: "font-bold font-causten",
  txtCaustenBold1788: "font-bold font-causten",
  txtCaustenMedium1341: "font-causten font-medium",
  txtCoreSansC45Regular16: "font-coresansc font-normal",
  txtMintaka3406: "font-mintaka font-normal",
  txtCoreSansC45Regular14: "font-coresansc font-normal",
  txtCoreSansC55Medium32: "font-coresansc font-medium",
  txtCoreSansC75ExtraBold20: "font-coresansc font-extrabold",
  txtCaustenRegular16Pink500: "font-causten font-normal",
  txtCoreSansC65Bold34Black900: "font-coresansc font-semibold",
  txtRobotoRegular16: "font-normal font-roboto",
  txtCoreSansC85Heavy78: "font-coresansc font-extrabold",
  txtMontserratRomanExtraBold18: "font-extrabold font-montserrat",
  txtCoreSansC85Heavy34: "font-coresansc font-extrabold",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
