import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Homepage</Link>
        </li>
        <li>
          <Link to="/productslistpage">ProductsListpage</Link>
        </li>
        <li>
          <Link to="/confirmedorder">ConfirmedOrder</Link>
        </li>
        <li>
          <Link to="/emptycart">EmptyCart</Link>
        </li>
        <li>
          <Link to="/errorpage">ErrorPage</Link>
        </li>
        <li>
          <Link to="/signinpage">SignInPage</Link>
        </li>
        <li>
          <Link to="/productdetailpage">ProductdetailPage</Link>
        </li>
        <li>
          <Link to="/cartpage">CartPage</Link>
        </li>
        <li>
          <Link to="/checkout">Checkout</Link>
        </li>
        <li>
          <Link to="/contactdetails">ContactDetails</Link>
        </li>
        <li>
          <Link to="/addaddress">AddAddress</Link>
        </li>
        <li>
          <Link to="/wishlist">Wishlist</Link>
        </li>
        <li>
          <Link to="/emptywishlist">Emptywishlist</Link>
        </li>
        <li>
          <Link to="/myorder">MyOrder</Link>
        </li>
        <li>
          <Link to="/orderdetails">OrderDetails</Link>
        </li>
        <li>
          <Link to="/signuppage">Signuppage</Link>
        </li>
        <li>
          <Link to="/resetpassword">ResetPassword</Link>
        </li>
        <li>
          <Link to="/checkemail">CheckEmail</Link>
        </li>
        <li>
          <Link to="/verification">Verification</Link>
        </li>
        <li>
          <Link to="/createnewpassword">CreateNewPassword</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
